apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-contact-points
  namespace: observability
spec:
  encryptedData:
    contact-points.yaml: AgCIIpM9Uq2KunH2hnZKDD0pAG4A/5lZkBOmhMG0b+j0epA5BhhlL70tDPQJVRXDZCvdlx6Bo/71Bhy1s1SxIzdwiCxsFd+UP2U1Wg8siW6mA+ftTBk7uBkuSg/3pZ44EWcIy1QqytxBbvKOx60LlZGNGO93W5iGWJSSHAnXS1t/SDHWQo1pYP3XvLS5FFqW7n2v/1IdarzIz4iqiywBCiMrdrEqDF9KZfb9thKgCgopo0NzLl6ILTaXNJVz8f0Q5rh1nKYyqr7+HcwAn+m0WfiXPg0v4/16aScJLUhO1vfhLw3km58jma4CzJCsTiPYPILM3JxqpUsOfMRgJ/iYrQwgm39CRn3IRDECjdZNZCki8H8CpGG97U+g3ZDFl6dKEH4fvQjLgs5PZfTsu1zvg885WiarnZEflZWBGzhOp0RJOLR7h4KbG80F7TJVcBWJ9RyGxD/YgDcTGVpVifem7XjokFRHsYSvjhC7o1A+sArOowXIHPkcxfeeEQLYoS9Ah3W3Pd8QkTTjJ1KSUkNyrkrMdJ3pYcHwrXkCD/dM7B4eSAM16HE7QMlnZMg+lGV41pGwdkCf2waAULfvztoc9XsAS4VWkkUDcSG0qXnuwyVXbuFZv8oVXQLWKL0zeyoMNQCNwl0xaOsUhfVrGnBYhTFUnENHEr7IVssgQGrLpVbH2ddxcxo0Am2cHrUeWfveJ7NHJ2JcUljNiMbVx+L6F97q7Vh7oe/4rVhCqBBbW7YM/BPXWAF9NpS3aXGES1cGSWlbvn7UeJhbBz6rw1yBofM+4EktCyvV0K+FUKR9+uBcsnIMh65WCv3Fjnft/PTZvoHcBXIQKN/ZdF0AT4fP+BM4RuOnDKCHtZ0+NvBKMg9I3K9rtdTfG/I7JyyzzSyKsWf1zoNCA79g4J02CFieKvz35qXNPm4vNb94amRU1Sg8WSjtBfEj+ToPbc8fv/D5J5qmrAELUctcMdiGwK/fLyqkA53CENYXjYX2ZUz6nBYPPItLHzwbDf61QLZWgMlUNMuyBD+WEFvGqqISJKlCQtbu
  template:
    metadata:
      creationTimestamp: null
      labels:
        grafana_alert: "1"
      name: grafana-contact-points
      namespace: observability
