apiVersion: 1
groups:
  - orgId: 1
    name: Thresholds
    folder: Custom2
    interval: 1m
    rules:
      - uid: fdv0br168nvnkc
        title: HighTemperature
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              disableTextWrap: false
              editorMode: code
              expr: round(max(node_hwmon_temp_celsius), 0.01)
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 85
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: 'High device temperature detected: {{ index $values "A" }}C'
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
      - uid: bdv0mb90xnchsd
        title: HighCpuUsage
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: |
                round((
                  max((1 - sum without (mode) (rate(node_cpu_seconds_total{job="node-exporter", mode=~"idle|iowait|steal"}[$__rate_interval])))
                / ignoring(cpu) group_left
                  count without (cpu, mode) (node_cpu_seconds_total{job="node-exporter", mode="idle"})
                ) * 100), 0.01)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 85
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: 'High CPU usage detected: {{ index $values "A" }}%'
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
      - uid: ddv0ncesazxtsc
        title: HighMemoryUsage
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: |
                round(100 -
                (
                  max(node_memory_MemAvailable_bytes{job="node-exporter"}) /
                  max(node_memory_MemTotal_bytes{job="node-exporter"})
                * 100
                ), 0.01)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 85
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: 'High memory usage detected: {{ index $values "A" }}%'
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
      - uid: edv0o9ih63pxcc
        title: HighDiskUsage
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: |-
                round((max(node_filesystem_size_bytes{job="node-exporter", fstype!="", mountpoint="/"})
                - max(node_filesystem_avail_bytes{job="node-exporter", fstype!="", mountpoint="/"}))
                / max(node_filesystem_size_bytes{job="node-exporter", fstype!="", mountpoint="/"}) * 100, 0.01)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 85
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: 'High disk usage detected: {{ index $values "A" }}%'
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
