---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-adminuser-creds
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBiZvZwuDnaAGT6HZ+IcI5ZUb+UBVsmJVH+/58i0Mep55ZK6vO/gihrLDJc99aelaqVutlkA02rBl1zial84E3ivNU2AnY2+oF2f/fZLs7iLHnSd8aYavLSY8+VBE1sI3yE/qeX4e71r1nfT/zPHv5KBmp2LtDRRg7OQTYXWu4qpzlf5x+FqfosuyoogL5eLeTzx07XNqm6BPUbIzkKr9JmAq+Ovt7hiPrsZd597es60mS+lWEzQebm7pmyNpbDjrKeVkASiDeeq/kckQfWQXNDDk+QsKgR8OgZxJzSHQbd+kammcKkVb7ZF/hFA4yIAlztpa/nCDrqrLy4uxJgmH1tc6y+3qU2mDtycums0amtl/D2OW8AqOpYDDlg/5r8KEe6ORKIf0oHsx43U/Vv6VhiRgDSqyDi1Af3CsR8ppWcUCQY69TuVfBCah4lG0kGqPok+3B1hTPFm5CaPWbD4N+g+gdWRmZHiOS4x+pS00Q3t+o9rI6gv91IfsLEQZypeMwzR2Dn50EkKB7AlzsoYdvS2759yj++MgM8P44ByMIzvcNbm18BEZA3WkK9onE4HtxzTb3zTq+fweeqr0fe6tIiEeUirBBHSld8CLI/G86ynE/oMqO5ZI+xzEQkovfxUpILenDAdUtFUFK9P2goiLi8muGX/0RjpPdbv2+aa8pnBbcEy3imG+KAJi5RoKHp9u3c6R8KYvQYtjHO3Drb5O+Qgw5qlFadvquLU6+z+ubPlTAQBzJ6pbfhr0mVc+EWdurpvQ==
    admin-user: AgDu+mtYQSlTdpg/UPZFNhlt04NEyCmj6MKSsrRZaUnYwDM0DPfRy3eqyWIT0qool7iIyG30FFPo39m/b+UuZVbG2+LHvRNvP0r+9oe6GEiut6tUdEh0d5TIlYSbm4SYKucI6gFp8OVuDLraoDzG6nv0vUGIwbTtQMWn9OSDuMDB+R5e6ZFWogje1eqPcMjECJ9LMA8XznaY2tO82LPa83Cs/0GF8tfI+r181YAEhulb4pI5LVJ2eNZoTcp1/Ord1cQxCLTJL7HwCaF7ePhnTjW/wDb7Wa87y2s58/8VahsgzK5NSRo8PRpzdhmt45aQCPwHPdk5K9hbv+KbBGrX08XYUuLuZwbG9A5YsTU+kUvimlfQtOKOptdniEOH+sQIajgRCb3YAZK42IJedLSwyE0X84/4Xb0+9t2jZsTEHU6sk312goU1Bu8XFtupeQO+KShfomxFsleiHOQo3MVBTOWdG2tU3IHv7ISg4tk/80Oemb/hE3gbMUbx4fZJxPN0QG1mSQfLULCNNydF12jZAxhLJAXYvt9Q5g2WJeLds7kKjjd6OrjPfdfymp2dm93DTY/Gnw8o0VLcP9s/vAGL5JtZ0g8oxonA9P4hVvrxkOABc1v9/z4cMyUBqKV3GcoIP70SLhco8Gy1a+Zv9BLZFhvlPTaGYENWRhM5+tPjHIK2bi5EeZMgxRhSfPeyzxl0C0Xn9PzaTw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-adminuser-creds
      namespace: observability

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: observability
      interval: 12h
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    grafana:
      admin:
        existingSecret: grafana-adminuser-creds
        userKey: adminUser
        passwordKey: adminPassword
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /grafana
        hosts:
          - cursedcompass.ddns.net
      # https://github.com/prometheus-community/helm-charts/issues/2837
      grafana.ini:
        security:
          cookie_secure: false
        server:
          domain: cursedcompass.ddns.net
          protocol: http
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          serve_from_sub_path: true
