apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: observability
      interval: 12h
  values:
    grafana:
      adminPassword: 9dfsC6qiOoEN8vqWzSM36h37Zg6x9l59nndp4qhxIdt72l8mPd
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /grafana
        hosts:
          - cursedcompass.ddns.net
      # https://github.com/prometheus-community/helm-charts/issues/2837
      grafana.ini:
        security:
          cookie_secure: false
        server:
          domain: cursedcompass.ddns.net
          protocol: http
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          serve_from_sub_path: true
