---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-adminuser-creds
  namespace: observability
spec:
  encryptedData:
    adminPassword: AgAiuvmZC/RYHPlUfgNMxKZ8fP5aHz4/w1kxgKQgGOXu3MEe8VKZ1VhIS1VC5KSPbucRZN0MZMzBRjJIdaBaWzWR6rf/mx2iQOJqUt18X6Jk8f7mo6shMYj0xjte4xi44Ad6ljQYdRDKgCCllDGOBLAns7p3Dg4hYjTG6dkdnyzvskRyOcBb5raiKJkmW5Hx4VCVBPzU077mAVfU3gL+cLl1QQsWjrViNu+OG4nRH8Ex4QZtpHFZqsm5ysGIh8nwa939WR5pwzp3u6jNaTx/15dE9sGe69Gdz2WyecZOwP/zs7fBP89iPvj/VW5O0z6DUWOwEFKTs1hOoXZ5qAvVxzs1ml1O7/anCrpcQMQRmNX/e19agesAYEFR9r8VV0f2cW9UJ3As+cGwwgmUpr6t3dIBzK17DLkldfsuXhth7NE/U7MezfD3OTMbbhCUvfyLv1lSQcbHlemboPoDiIZKw0Dm3ft7kzXKtJFoX2njDeMZkIpXGgEItGKX8XEztZ7iVrM2rJiL2oYdcTfkUxEEhTEu2rSadEaoNzyT31T7DHssh0W8yj+y4cf+O8M2XerpJEPuhU0ko1WzkWQyrQcdMb7BAaDKRrwpoV2IL1j6f6/qY3DkIJjKXDA0jzs3ZiOAa/asUcjoiEwZyhmI4fh46joGThRSHCQ+ullcAweLyHPP3vZwBZLzwsweW4ai8D9sTjG3VYYWVle5lITwqo/0Ok2/6KLoeh5KRHRasOkKo9T0bazrgnZaSsMQgb6PmxMZKat08w==
    adminUser: AgBo2NiWRiRXaZbmwwgYbdvwUN4xKpr+TE9KLj4jeET2SRhnmIitMshsiOxPTT6nEbfM+nCG5Bk2iEFXODsjGgnXlf1g1T1wPHUD4jX5cdqTERvclKz7bgVKuyu+0xmx1j5LePFFmdUxL2sOvVRgEtF+hLHBvdocCXds2yfmWwsAjlTBWIOJVPp5c6Pzdt3OyocCczoDT+fscHnHlDzUIrKXM6FYv2sAVJ7TtOdYAc0N3eku6G7DfDyKTNDlQR1YIK0E0I8ahwA6MYBoNyvAdKdCr0CfjyTymJ7YExWpcuExxWjDcEzk26O0oeTFnESFpB8e3kisDLX7aclCvaxHzqi1b5nRTAbQEuiCtAwqbPEWfroVLjH1WEtACyhO66tC4eJRweHF5QxzaE/Slm4Cxqz1c1yPpDw4hVk+pHtttmi7kPNY2VVYw818egu9rn62zK0PgygxEU83oH+mNIaM3Vs13slzZrySFm5sCU8bLDxY3OtfU4GEFshGfZbijmoJuxpNpicr3j9r+dqGXzFVv1C9a/MkK6p8ytVTzkPZPuIclkTY29KTyH5iNxmAKObFWTJw7CRmtBzCLJM1UUzlUiU28q/tWH8u4tU8Als6CUZ5GhyGpaJ0giNOj8fEhU3SZN5TnhLwN1F7P2jZnLdUrO7/KbAaCbsgE3f1ErYZr9rSIjAbqLVnsgjRbCOmKqihvF69EFOLkA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-adminuser-creds
      namespace: observability

---

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-smtp-creds
  namespace: observability
spec:
  encryptedData:
    password: AgCN7e6Cb+plbdpRfkmmdGCkvtmzekoy4NycT/m1cjsh0kIJhid4gWkUjqrsWp3VaS1n8glRKCSCtLsJoyWg1lqGCgxSg2nsVhJFnPbwDUhVjlwEXo2MhRu8b132LHBUJNzBmvXTHXHP9GQ0/kMGAvZNJ1Vd/v4hAo2AWbmSe4iTc/tr1ASGrzvandSazQZ95vVGtax5RHJRvsIZQiqsWTv4tBy4ybolpn4jOMKALxVrz4SO3bEnANhW8Mxg5E61rAbYX0jeIg0bD6iQWtzpWFzXf8DOzC8pgohXUKaBDbK8s1FOvGikV3bpP/nT66eMUwQ++Xp4okBJQIXEO83cKC83hVEoFw2m+2k42W/HQ8lfe2C1U8mPPUtBX7TG59q3jeDOjZYH7KnMBk8SgQgmKDRXE9fklSlagJTW0dDjK5iBMj7m/W+lcKdvMkdlWG7RAgDoCrX3ErRdg2HhRiHaZ9Uagz3668gnhPjFZkI932flT7XkEgyqRjFKRuGUvJDWoaXTwhLsasSceGb+QsexJsvkynFBMZrAOxWpeuLkMBFCVoHw9zmwr0sxrRu1uuTRjGGtQf7adttmJAU3Yguyp4F+yp5a0RUM6R8DnLgAAmBIXHqafKp3b8YZikafJAeB+y+w2i09VLARfJ2JgsWQidUfrcUqx1oxKnSTk+/tkKG4w/VjJ/apO1wXQya5FKmXu4x8ZFtO6Gx9Azgd7YkuIxXoC+wkwLQqg6VYzDvdiPGz4Q==
    username: AgBsC7IN0OVp4od9rAsKhiNmS6ueTlYqh6VR0EL5KlDhRKNCRahvPPuh3QlZPv1bE7uWxQ4TcF4tJAWdDKMztfS7gBxTvquhFYqTmkKTqUcrIgI19bgW8k0NlGfBL4pzQL8RUkv1VmijJx9WcP/tpirkeZ7yly7/u1gpB1/vHUWPbWVFfTxDWbNeIpQsdI4WzHYpIakMHM6OSFj5kttCG3pY+rjjlC8wG8GDvXWhT31GnLBPtit82/E1vhj2dbKqlgbsTH9d/zXwkZwBRchxBhl1VXkE+9Cb+GRG7Ra6WjuBz7HXWZZIFw8ydFkqokHpZvOzhsOfqMNKkL28GQu65cXBD2Mo70a8pQZhco397gXzzvBQUfjyegpcHWIKaiFCaid2OIIWmIhgScLf74xH2TW+wjl8Y9ZRF8CTiVlCTkXqSzYtTqUhjZXWkD+RPi3aemCmyfDK5yPJQ9vJ94oUR7zAh05OHgsbd9PJ3x9duIAHcOy5VfEd/6LCtSvYjWNn0RfQY83RaO0htiaktiGwI2Q+srAcCcHWelczZMFiuwmm/UEHbtUXQDOTMkQl2ShoY3Yu0fh9Rp9OJBkLaexrJVlG0LpXESfvy3n1G+7pTA3fvVQ1kssoIf7KJ5BRLJU7Mgo9UmVulLzoIxVtd6ykpQvtEg/AkpLLC1zXFjwEu3gT5QhH/nsVt2shdqLT4AfOZ4OiM8g=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-smtp-creds
      namespace: observability

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: observability
      interval: 12h
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  values:
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.242
      admin:
        existingSecret: grafana-adminuser-creds
        userKey: adminUser
        passwordKey: adminPassword
      persistence:
        enabled: true
        size: 5Gi
      smtp:
        enabled: true
        existingSecret: grafana-smtp-creds
        userKey: username
        passwordKey: password
      grafana.ini:
        smtp:
          enabled: true
          host: live.smtp.mailtrap.io:587
          from_address: mailtrap@demomailtrap.com
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
        alerts:
          enabled: true
          searchNamespace: ALL
