---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: observability
      interval: 12h
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /grafana
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - cursedcompass.tplinkdns.com
