---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-adminuser-creds
  namespace: observability
spec:
  encryptedData:
    adminUser: AgAqVMtI4V44nIv/254IhQMsbNL4imM92ChTYmD/kqSllLUzvEdVmMXFv8jeUoYDTPLj2LUk0K2UMgnZM+86nXsGYibNvWPS64IpVlF7sNGRjD/shXWc8fdQq842Q8K32trNPpfqr/E2eVs/H3CwVdzGKXZKMkYhI98Jb+qPeXwQtp1MBEkR025G5OQxsol6SO7sVhtHQiVos4cfuBWZSOpydQ2YBXYF6HDkG25TTXj7DKj45wWWy0aOchVnkDmT4RfMCsuMaLzKIDtuNrHIBN268iOhbaqNHAxSOaKstOC9vrifTzBnJV6W3ujMAMQyWDXU+6R1rXS69c5cZ2EaZjM5NfdaxUjOXxqzhXQtT4NkgB2JH7Zn7vyrfIS17s0k/JhjbNB0jSD8PoNxAaRfGJz6YsuIV74tANsPFQnnff/WJ3NOHlr2JqvxmFZFgEaLZy1QLaOMrvyes73XlHuaThkHjFD9CGgEgnjQNjxSMHSJOmSxwlfwoeWqy6WCd1IB9Dk21s3Aiwtr06KG2taAZ6lm7uYZA7afS5yYYJPrv+tNwPHC6LrdtZR0HJgApVloLCx4i4ZtD86+hVPP9FTws7q628nJiYB1SNxUGijzMrfFkAa6klhLRQVRC3dVsYS25W490tT/0JeqqfxKwERPEerMjH3vXVXYWFVMMU5Q2Ek4djH3baG14Bttua+IxBgkh3RYoRcB4g==
    adminPassword: AgA0Uai+Fw4uzf4MrGjj2J4WZvAu23wHa9n40s//615cyPPKoD9r2MYF5RPH0qTOzly03YuQ7PQDvmS922JdA0noK2Qyl6nvNUU5PtukG/uFRgjf4e0knjO1gHorcp/ODBNyO0VYBclBg/gjsUmFfUs/B+mKQ+4GMroVxW4qr7OQM9JgCoO0w5RdRl34o5t/15cNwi4NfdeSlxIW9tlzfzBv2EUEziOSrePcdHDv+wWlISUskG2/a8G0fkuDvL27TOJuGw6NGXPOjbg1ayTBhPxpnwZXgk+meFhHS/i8ioT/wvHd6rnwC91p2QkSCc6/ofTFgqWEA/wVyZqiXu3zS7leehYw1AEl5rea02WEbpy2EOIK7f5Q0WEvEZNvaBWvMfGjz33xVb6dXuRXfonmUiI3PLuFPBn4oT5y9oHEBPDCD+EzNWpcHv/mFISGOsq6IdQct8WD0TvllXm2uluCYiddyqeQdKAHipA7b6PneApkwRhfaNy9diWBoSxdqmCE1CmZUvEqCaKD2OoYfUJe9aASwZv2WRU9zHGfdUBCUYqb5VP9CvT90QTZj3Om+Phn3jdMCGH6XpHcMuCidroecEk5d9Ej5bGo5aexD4AY/viD9DP/ILFcQi1B3bw2PAebYrOZGJvf/2gvOzH2HcODtUlhWfkqI69ctbA3vVjP9XNYA7yxd0h604H1bUw0mRKTM+Q1kuOLEkIp9ZRQVftkLW52DKhkdDg3R6hT8w0+IEFLLpsnM4rYqOiE8aF/y7CVIdGnVw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-adminuser-creds
      namespace: observability

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-smtp-creds
  namespace: observability
spec:
  encryptedData:
    username: AgDIfxLmiAc0z93AO0y6e5Flqr68eOBPUzUzHjxLgBawOq0TA59z122x+Icz7qkvbzkHaZ01DxV6Hf+g8P3oOmJni7iLiw8fx+PJomGN95Yk3yJQ4j/53Szn6qLnze+gd37FjCrPxVTcFkfUmeyAU/PF0i00YXL9qMO123r54ilaO0485OuLwFQTdawZzDRThmUIGrvMaCCLfmMb5ur0+BGSPtcP2LRmKt7v30N5EzMxlmlY3FNzG4eOl/VJGxx0F8YkTGbytvmr5liyNx/ryJwdbUo2/gM9m2wMvQwiV+e/wxre0wXoF1oeX9stoh1ilBzVrnLsiY+zMqHRIpHngpx1T98jgwvj0OWIevu69SKlCduMHrt2JbFI71cpEnDExWxz0Zv5uPrCKVKOcoSAS3/qwB8w9vZ16vHkZVrIho3PXsCHi2OiPatTpwhOQEx7qhTcE9eMYWdmUKNL22IlprykFULcLOQ+7nXn1liVA2CkPfs6JsIznT004GEFP4muFC9HTF2T8I97HSZgxEuhHRvK1CsG8zhlokWlUgsJENDhjrGzQK5RWEpXnOJ96CtQbkgmQC0tPXFEph9LDHg4J2w6056KIw/gzkRJkuQBbHD7EMf94Z9B0XV3FTQLV2/RCxwOEgjUrQEZFbj57H4yqTj+60fILwvXzoWEwbK7kRcels66ZWV2mF52dABQoeqO85aQOUc=
    password: AgDkCLzT2uTnzQ3xgsIo/nHWSWNDDq+gpJhsmXNnBjXZXn9HTIvCYpGsoL2q8CFTJmrFqtWXcnvG4V5QDObkpg92QTjFiWJVCOnehgddJBvbPDt/EZN/FEklpieTIBgC9G0uYbA6Q15Rf7GdeZZcYvJCUjLHlOeYq5AMS3vLKNy9zTZEQ2sMM26NjWb5m0ty9zml+UEDWqjIuGsCtwYXwe/63xvtyfhHMwTmN68E0i0FQQYjMa5juFf9I+kwPGBkFaHPFpZXF/WRN/xljs0YuC61cDrVuB+TCXNxRQfqqIT8rfPQ6hF7ALrzXIVuNONPhjErYI74YWXd9OL+wDywEjQP9cQG3ytOIyxM1hdtxXZADQjsQimh7U5VX3vNF79+Jc0KCya0++oduOPAYRqAYjriZ8emWWWAAIhcdSylyjPgzPLVNJ7+BNMowvkOlrxOU0w8VXeoS24q022oHxDGIS8JQ3iTMHdPtTn3c9jjKHpuNUElStTkujrP1c3/EPJndWnjT1M+VpyMTrsiwpI45ANZGAll7wl4qPZtO3XTWRRDgC16EXBZ6HlumVgztbCBCL8RG0tmTTRjX1t1vW2cZ8x8Mq+CTJM+RRVY6JKIYBSv5Fun3+ldB6aXjYSJG52RYeYp7q8JLamU0XawDzQ8uODyAl2xfvXCh5qcBoQN3vgqWT5Y4Z9kTwR5To5Mn6DpMTEEOko/46WvFDUEa1K8yUMcNCuxbSGacnetB1d8fOHKeg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-smtp-creds
      namespace: observability

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: observability
      interval: 12h
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  values:
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    grafana:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.242
      admin:
        existingSecret: grafana-adminuser-creds
        userKey: adminUser
        passwordKey: adminPassword
      persistence:
        enabled: true
        size: 5Gi
      smtp:
        enabled: true
        existingSecret: grafana-smtp-creds
        userKey: username
        passwordKey: password
      grafana.ini:
        smtp:
          enabled: true
          host: live.smtp.mailtrap.io:587
          from_address: mailtrap@demomailtrap.com
