---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: observability
      interval: 12h
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    grafana:
      adminPassword: 9dfsC6qiOoEN8vqWzSM36h37Zg6x9l59nndp4qhxIdt72l8mPd
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /grafana
        hosts:
          - cursedcompass.ddns.net
      # https://github.com/prometheus-community/helm-charts/issues/2837
      grafana.ini:
        security:
          cookie_secure: false
        server:
          domain: cursedcompass.ddns.net
          protocol: http
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          serve_from_sub_path: true
      additionalDataSources:
       - name: loki
         type: loki
         url: http://loki.observability.svc.cluster.local:{{ .Values.loki.server.http_listen_port }}
         access: proxy
         version: 1

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: observability
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "5.x"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    loki:
      auth_enabled: false
      serviceMonitor:
        enabled: true
        labels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      chunk_store_config:
        max_look_back_period: 24h
      compactor:
        shared_store: filesystem
        compaction_interval: 10m
        delete_request_cancel_period: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      limits_config:
        retention_period: 24h
    gateway:
      enabled: true
    singleBinary:
      replicas: 1
    monitoring:
      dashboards:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "6.x"
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
  values:
    test:
      enabled: false
