---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-adminuser-creds
  namespace: observability
spec:
  encryptedData:
    adminUser: AgAqVMtI4V44nIv/254IhQMsbNL4imM92ChTYmD/kqSllLUzvEdVmMXFv8jeUoYDTPLj2LUk0K2UMgnZM+86nXsGYibNvWPS64IpVlF7sNGRjD/shXWc8fdQq842Q8K32trNPpfqr/E2eVs/H3CwVdzGKXZKMkYhI98Jb+qPeXwQtp1MBEkR025G5OQxsol6SO7sVhtHQiVos4cfuBWZSOpydQ2YBXYF6HDkG25TTXj7DKj45wWWy0aOchVnkDmT4RfMCsuMaLzKIDtuNrHIBN268iOhbaqNHAxSOaKstOC9vrifTzBnJV6W3ujMAMQyWDXU+6R1rXS69c5cZ2EaZjM5NfdaxUjOXxqzhXQtT4NkgB2JH7Zn7vyrfIS17s0k/JhjbNB0jSD8PoNxAaRfGJz6YsuIV74tANsPFQnnff/WJ3NOHlr2JqvxmFZFgEaLZy1QLaOMrvyes73XlHuaThkHjFD9CGgEgnjQNjxSMHSJOmSxwlfwoeWqy6WCd1IB9Dk21s3Aiwtr06KG2taAZ6lm7uYZA7afS5yYYJPrv+tNwPHC6LrdtZR0HJgApVloLCx4i4ZtD86+hVPP9FTws7q628nJiYB1SNxUGijzMrfFkAa6klhLRQVRC3dVsYS25W490tT/0JeqqfxKwERPEerMjH3vXVXYWFVMMU5Q2Ek4djH3baG14Bttua+IxBgkh3RYoRcB4g==
    adminPassword: AgA0Uai+Fw4uzf4MrGjj2J4WZvAu23wHa9n40s//615cyPPKoD9r2MYF5RPH0qTOzly03YuQ7PQDvmS922JdA0noK2Qyl6nvNUU5PtukG/uFRgjf4e0knjO1gHorcp/ODBNyO0VYBclBg/gjsUmFfUs/B+mKQ+4GMroVxW4qr7OQM9JgCoO0w5RdRl34o5t/15cNwi4NfdeSlxIW9tlzfzBv2EUEziOSrePcdHDv+wWlISUskG2/a8G0fkuDvL27TOJuGw6NGXPOjbg1ayTBhPxpnwZXgk+meFhHS/i8ioT/wvHd6rnwC91p2QkSCc6/ofTFgqWEA/wVyZqiXu3zS7leehYw1AEl5rea02WEbpy2EOIK7f5Q0WEvEZNvaBWvMfGjz33xVb6dXuRXfonmUiI3PLuFPBn4oT5y9oHEBPDCD+EzNWpcHv/mFISGOsq6IdQct8WD0TvllXm2uluCYiddyqeQdKAHipA7b6PneApkwRhfaNy9diWBoSxdqmCE1CmZUvEqCaKD2OoYfUJe9aASwZv2WRU9zHGfdUBCUYqb5VP9CvT90QTZj3Om+Phn3jdMCGH6XpHcMuCidroecEk5d9Ej5bGo5aexD4AY/viD9DP/ILFcQi1B3bw2PAebYrOZGJvf/2gvOzH2HcODtUlhWfkqI69ctbA3vVjP9XNYA7yxd0h604H1bUw0mRKTM+Q1kuOLEkIp9ZRQVftkLW52DKhkdDg3R6hT8w0+IEFLLpsnM4rYqOiE8aF/y7CVIdGnVw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-adminuser-creds
      namespace: observability

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-smtp-creds
  namespace: observability
spec:
  encryptedData:
    username: AgDx9GA3ot/IrUXb4YSOQqzQIqv/Wdux0ePzSG00pV1DJ//mtnYNGbmlPKldqc8P3LxGxJgVO/1Ay4axG1q4Ev7fePPriRfRcBsC+2zmVUTkoc4GYUUYgDBU3JOf4pJWNCsxJcBQ4R9CbL64bE8V2/qTZ9D7LMPianVUeyXh6tysezYnhKP6gVfakxSOfSiGBgwYVLumBMVrHr/4DHW0vW45hbdmqnxxzS6sp85Wn6qzldg9N7k0/eGNomskXhAZAIxa0mFZ32iuDwvPkbgqnzP0rlXnHIfmsxXLN5caFH85lpBulUU/Rr4R/JnwXWtAUZpE9c3dnexHJ9O9EVy1GLv0GSryZT8eQDKb7Un+o/fqs7tPizCeIjOXJHRwEVknxk2TxVkcjX6ZN6f1MD1h6axxyWybGv4MmKQtRvylztU29vHqwzH4qf8DrlCk0m+6rrUXxc5Yyp+3n9EyIcA/N3ROHsT/UVMKj2Lh/z1BobNkCaJUsYyYPXJJcwgoKC7jL1Mfh/mR6tCeC6RKZIY+aSPFHQwEvow/4hUNBubX3mv/DmnXt8Gt3fGic9CHotQpgILr8nbBYsXw/4kARY7upt3bA6Rf18MKLGMQFgdDp6Y8EfYJVo7H2FXdIoiqm9QxKXuUqcgHkXakZGxqM12Y/crOt+9zPAoYpcuEs3T7ils4x3NjpLrL6pUTdElc0J5lMISwT9bwDtDgGcRjOKNmtQ==
    password: AgACG/X3gWOw/gcJlbVFt0I0jBykKAlayNYroQIN+t32Muye6e8/Jwh7XieC4EyxdLQzFigToHTK4BRnZOieASs7GdscfMLZJl3yu+1nI+SIjHzXEK/6Kru/BfOhPtusHMcdxgbMaCoWmBne1lWZoSrghQ8sIAEjfQH3rCltawwTkFaJcHUrRHkzSNUNZqARyQAyeP6C331nitDO1RIFcochvLDaHpnsQ9IFdSoDMTZIVyjdgqB1QVLuxwvpr9YqF/7x8mxwaISMDlUgsF69iOSBRuj6cW+TUpotMZ0jwhwSqu27F2x2/UBD3WPIu4dr4PJafky00rF1P4rpuQy+DzF4YF46ACsqx2Ld8E6Ed9Lj7RpFMPV7BwIYzpJTFwVpNdBxLJcxCZTShPcamRvBK/Qmit2DgiSk8l9a4SdwzH1cDbQM89+xvUK3xeek1PeTmBN/bwZorGyah8d4ccxw7TcoDKiBwCfJn5nzBc9SpVIdoSWVjpSib8qI0xh3hi8O24kpn1Z7PF2vqStA/l15v/XCHue2SbmkAhaJrGn3hd0mYHi/FBucqcWcBoB/Al0YoUJzDPpS8zcw0p5uA/DDI3L2uOqS3razaA5EbMQRixE70iw9CwpiszlC/si2FypF5TuiMEkYhrYW9zumxyf3LS2cusn61199Hff8EhkP+Xq+5rQ7AUm3HjdkgnxibPAxWjOCSBgZMh1485v6XXkMAw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-smtp-creds
      namespace: observability

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: observability
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: observability
      interval: 12h
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  values:
    grafana:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.242
      admin:
        existingSecret: grafana-adminuser-creds
        userKey: adminUser
        passwordKey: adminPassword
      persistence:
        enabled: true
        size: 5Gi
      smtp:
        enabled: true
        existingSecret: grafana-smtp-creds
        passwordKey: username
        userKey: password
      grafana.ini:
        smtp:
          enabled: true
          host: sandbox.smtp.mailtrap.io:587
          from_address: server@home.com
