apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: grafana-alerts
    files:
      - alerts/custom-alert-rules3.yaml
    options:
      labels:
        grafana_alert: "1"
resources:
  - namespace.yaml
  - kube-prometheus-stack.yaml
  - loki-stack.yaml
