---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loki-stack
  namespace: observability
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki-stack
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: loki-stack
        namespace: observability
      interval: 12h
