---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: metallb-system
        namespace: metallb-system
      interval: 12h
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
  values: {}
