---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-gateway-token
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgAuYYMeNlrYZ6iCX7uGQjwMyD+N7vva0wFM/F23+gnADfzW2I1HEIcw49IwsmnQzJFy7UkvhrcsME568zMr/aP4jGe0z8cApbvr6bj+opfA2XQEkxD3hKCmnG+A+ZdgdeHkW40ydqp5Q8j77LhFcRA8/XLTgM4SQyT1ngRjO+Sle0nkjAhxqlX2ApY42fhx/3ucdoOPyCcsqROB5NlFnE5hKICIos0KVmgIprvGmRqyHxn9WieioJWZH5Ryl2CtYVEPqvWyd7K3Y5tTg1k5kDrVTJgEORxVDh7QMiFeU+jy+cHA8FUC2Ve6d5rHdmWkOj4GNM//DCRvy70hxofvfRN1vGp6wKVPuOctTLfRcflroHY32wC/4PBsIHGiqam2AU6b+J7w/+ijuMyFXtdgmMLwO7uafxWQ4kz/FxMEa9s++MpTbGv3paAoeZ04eeBSXwe+rPdJE4YIWhWs5QAFpdnZDzB6P0iVhKB9AVE34guyfgXg/8UWk45wWCxxsUEaRR4qAwjRBNSmyefdUCNrPw1Vh0sZ27H9nIf2p9ctLpe/7y2yWDngD7Tx0k1/vOfXkCWSD+dQTMhL1v+7PHvwzt53IqA/nEb74MXaGQ0o2gJh21NJU4SLZ8fbP4NAU2frjPu4IEMTGI3WBOjMPHcdbok3VToJLk4XcpJ81eN7kaV48aFsXcW3wdmRjoqXcr8rZ8Q1UJ0wSkRL5n3h1Qw8zjB7ZDTZ5klEd3MsdTW9LY2KVlKoF8eFUc3CTvJOJCMm9aac/WNAK3z1Af7FKkfGL5p2
  template:
    metadata:
      name: openclaw-gateway-token
      namespace: openclaw
