apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yaml
  - openclaw-image-automation.yaml
  - operator-oauth-sealed.yaml
  - sealed-secrets.yaml
  - tailscale-operator.yaml
