---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgASGll6hj7lr+oHEm2PO0uEF/8JA8aUBTW0oMO60gjV3ER7+oAI2nquPMqqCoqhEIILAUAozDZh5MDyKdTag3gj0QtN0mrl0sAB0cBIYi8qENp3z6DztESDjmVgP7cBHWjEGTQqncFUsUQtNLQyh0C/1SqcSINusEYZEoPeyr6gjSQIGmVzGrA9ocZ9riClgjo0kre0Qeig8010+VuGZLd+Eft8uo+h2yIgVD+WTdb8T64ge0OUikqJB5fYWO7/EZS4xM8EocamCwNZDjLy2lyfug1qyzRteigJaAqixmD5bKL3hb788NJy9g+CTCpxBQXl9iQZ4LUZ7zuN5Pdf50L2vvD36+JqsbewPkat1PlVjNUpSUL90aISePsYKN+I1fHNkl7Vc0kBSiQtZ/ePEgHsMR0zoPywx55pGGBW5e+H50XXkzCLEtd60k0NeQOnppuQ/CmQGoyL5bF3dn2XUGYVz8JHsabgxcbDHw4bwRbtrlzet/7b++LmoLI8whLO70V4ty2yijZFV08bYaPhhNu4zJMxCzEPRmCaMm2NQQqaXxA/8kZ8WWQxdfGovwbdhUiFl+l0r3O+YYPnk672pb3Z2438rEwo7+cRWrExTMIX8XOkrRgVpZ+Kv1kmyLpAE1h0ialXldM05rOcnflnWg/FWh+pktsopoFppCVYH1jS7eb7TWvYbW4hmd2s17UxuS4P0DIAUZ9QwxUmwddWXore4A==
    client_secret: AgAJ1rq8jzMtyYtKneArfMFkuaQUg8Ju+xegyQI/xkv5LK275xWuYCxCIIplaSuFnWpyBc2kDbuORePekn9akWoRufbLaNRexi9o5Ja5GsVQxbhUhQVuQrLAe6IOlfh15UpB+Jg38jhVo5dYvoZpR6NSsdDhRPQT22evkp5FmIzjQAxboGialCm6wOf5qviKVfyvv+e42dMqwq0HhQql4wkrWaUfnusdG8wSTcdUd+U0sFXafXpZuzGDfQPRhrsCZZZ7imbUDvxmoAWYe7CYjEVAn/vAgPmPEmGOYxd/+7UcMB7gf10boJOaDYKu9+OKxfe94duQ/1JlBhhe2FL0o/Toj4MzcT7ejy+AwPqhQqYR0ldY3tznbHQVWuUQwbK4aOMp0D+2o3U/i5naSk2xsovKU+d1F0G2ZnRPmTcsRPDRekAEwyo3ZRiGI1ETLR7i6NyTvudX2mkDnKXt/Z//jUpr4abNCq9XPtTuU0VUKMx+q9bh+rxN3fMqPpjbUWDGTpSXpIhON7qnhwdug8SoA5VWd2bnVgwWaTC6BQHsIUe/bkrKCg8Ir6/ivEl+uvmNNAis++5mEeLLn93wwMn99bWYDlH5Xja58Mm14GQo9xntfkbNn22Nbw/bsFYcuXABzYK7wnlE7uR2FPLG303rWiS77j44Z7x5eqUCvqDFjir8QxTE4QtqwnJl5G+q2hQlPffk3LBU6v0beL8c8EwryG46NV10VFfB3BkuTcpsK6PythC40r9FHwWVyJJRDgFn/RCQgk41wMzJkewwrw3p5m8=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
