apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/minecraft
  - ../base/pihole
patches:
  - path: minecraft-values.yaml
    target:
      kind: HelmRelease
  - path: pihole-values.yaml
    target:
      kind: HelmRelease
