apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - namespace.yaml
  - secret-adminuser.yaml
  - repository.yaml
  - release.yaml
  - tcp-services.yaml
  - udp-services.yaml
