---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-adminuser
  namespace: pihole
spec:
  encryptedData:
    password: AgAnwW72OyzEarictklgMbmV+4WU2sYN7tUHFpkwbFNS/HlT8HmDn8HyjrgSzbHGm410MR8rFV//YSXGWuRHQtGjwZlqn/k2C0R4x3CL6fXKN5/rfCTLeia1Tzt1JUwhtri7ik2F2UGe42BMP708Z8Q7XNVi2Qf1cTDsrTPwabhJkIgFZUVpLEM7ng2At8UAksrfcA8vkmOfwwcOP/q69lP6Vosit5SAWutNLQ1tiTEyOR87Aw41fT4qrP0S91ivZk3/s2KlPy4IBeLtxVPrHG3lfrBKGJ73UvGBW6Nsb+XEZM+MK4yl9OP/uKxAUmoj6Qm6pX5yslyo8uzruYC7hU4YzZHRpMFpmRo9338FvaBLGEB+/GVDvOxO3+QgnRdHoFXI/HJskrKNxXAL/eiTr3O0s+vXZwC4/P0URop/t1rolNsZ/ycICaoMsIizKYN12BKDXBlyG/3PLv73F5DYeT0mBacErBTubv+h8agOI/KXbNk/sN5lNOwhzA58Ft6YSmQqt2GPGZIqxyECTqMSIucjgyKQR99Deogi0abw1UujB/1AvHVIY2u9SaqDAQyJKnsoHKFhOBzCGEHK9/hzPBDYmCZw8rGovAotM7z3qrNM91WZESdvz+CehV7kwfqoiXXK65akn0ylkdDEAlEqcuu0ahQU4KOoHXjFmRwtRRkQ2uuzFh8hHYlg0siCY2qJA9gUX0NY4OZSLFwe147kEhlu7/6pf6RPL1F4YMvyJmltmE+4P3nLkgO7NbzN3VFXV+oq
  template:
    metadata:
      creationTimestamp: null
      name: pihole-adminuser
      namespace: pihole
