---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-adminuser
  namespace: pihole
spec:
  encryptedData:
    password: AgCfHiTKdaeewhyOqlWd3AurkXgaXuGyb8wsE407w5FAnYeUK0LhWNVZxVRZO3DhaJeXF0vow9p9fRLXty53Pw4lYsmMqGD862wIuyeN9x1nS4Cfb1Mh1Z4aFK3J5x6wBzLT40qEQQv+5BrjC1zqRaZGOPQgfprUzsKSExqYgpd5QobdYcTJvU1eXO1KmQUbY5lyk0j1/prZPAfHj3mUrZMA7yo/mC/r6MRnlFxN9ciS/ZDWtRWNDIHbFv+xODip4apYYwFtKDweAEyYotYmpDtEjgp/h3/lOTv2rCaTomtvg+1WGH1QDyBTEYznqDKLnz4iI3GszBZRtWaZPRFBNhpQu+QA1TMHz2qrlNsOZkahrtG0/k/n/6V9b8CvCWTHfzsZfcCL4ruc5505F+HP/yTIivy7TEz03VPpS2clLpf5VQDRumyaTNSEHf+n6wlWs+Ub+uc1oi419V+TRe1qC+xDc5bwKyPlZJ+GKz55pPxwmmv2uPp4zHBu3K79xK+FexVoMSCfp0PI7Q1z8JovIjmkNxt/njZcNxoFIUjxjNwrUz08mrD3nwWfY0v2WDM/VADIu6e+W3BbvwTR0ddxu/Pj8JA1z8FQkTIgVsLVcCOCSljAKdXvTXwk+UcqYGDU0iBqQocaryHEew63l+BdndjDrpKN3ryK8BjYLOVMPGmmO6TbJjFO1CQjumEkPpt/A11WbKGPdwHg5iqvs9kFBUUqdGgWkbwOmFqacZLHGM57v1/bhxRsEnxLprsqQmvyweLw
  template:
    metadata:
      creationTimestamp: null
      name: pihole-adminuser
      namespace: pihole
