apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft
  interval: 30m
  install:
    remediation:
      retries: 3
  # Default values: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  values:
    resources:
      requests:
        cpu: 1
        memory: 2048Mi
      limits:
        cpu: 3
        memory: 2048Mi
    persistence:
      dataDir:
        enabled: true
        Size: 10Gi
    minecraftServer:
      eula: true
      version: "1.21"
      memory: 2048M
      serviceType: NodePort
      nodePort: 30000
      overrideServerProperties: true
      ops: CalvinHaristotle
