apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft
  interval: 30m
  install:
    remediation:
      retries: 3
  # Default values: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  values:
    resources:
      requests:
        memory: 1024Mi
        cpu: 1024m
    minecraftServer:
      eula: "true"
      serviceType: NodePort
      nodePort: 25565
